function getauthor(d){for(var g=0;g<d.length;g++)var e=d[g].name.$t;return e}function getmeta(d){var g=d.substring(0,4),e=d.substring(5,7);d=d.substring(8,10);return[,"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][parseInt(e,10)]+" "+d+" "+g}
function arlinadesignTicker(d){var g=document.querySelector("#ticker");d=d.feed.entry;var e="<ul id='ticket-wrapper-inner'>";if(d){for(var f=0;f<d.length;f++){for(var b=d[f],c=0;c<b.link.length;c++)if("alternate"==b.link[c].rel){var h=b.link[c].href;break}try{var l='<img src="'+b.media$thumbnail.url+'"/>'}catch(m){l=""}var c=b.title.$t,q=getauthor(b.author),b=getmeta(b.published.$t),e=e+("<li>"+l+'<h3><a href="'+h+'">'+c+'</a></h3><div class="tickermeta"><span>'+q+"</span> - <span>"+b+"</span></div></li>")}g.innerHTML=
e+"</ul>"}$("#ticker").vTicker()}
!function(d){var g={speed:700,pause:4E3,showItems:1,mousePause:!0,height:0,animate:!0,margin:0,padding:0,startPaused:!1},e={moveUp:function(b,c){e.animate(b,c,"up")},moveDown:function(b,c){e.animate(b,c,"down")},animate:function(b,c,e){var f=b.itemHeight,g=b.options,m=b.element,k=m.children("ul"),n="up"===e?"li:first":"li:last";m.trigger("vticker.beforeTick");var p=k.children(n).clone(!0);if(0<g.height&&(f=k.children("li:first").height()),f+=g.margin+2*g.padding,"down"===e&&k.css("top","-"+f+"px").prepend(p),
c&&c.animate){if(b.animating)return;b.animating=!0;k.animate("up"===e?{top:"-="+f+"px"}:{top:0},g.speed,function(){d(k).children(n).remove();d(k).css("top","0px");b.animating=!1;m.trigger("vticker.afterTick")})}else k.children(n).remove(),k.css("top","0px"),m.trigger("vticker.afterTick");"up"===e&&p.appendTo(k)},nextUsePause:function(){var b=d(this).data("state"),c=b.options;b.isPaused||2>b.itemCount||f.next.call(this,{animate:c.animate})},startInterval:function(){var b=d(this).data("state"),c=this;
b.intervalId=setInterval(function(){e.nextUsePause.call(c)},b.options.pause)},stopInterval:function(){var b=d(this).data("state");b&&(b.intervalId&&clearInterval(b.intervalId),b.intervalId=void 0)},restartInterval:function(){e.stopInterval.call(this);e.startInterval.call(this)}},f={init:function(b){f.stop.call(this);var c=jQuery.extend({},g);b=d.extend(c,b);var c=d(this),h={itemCount:c.children("ul").children("li").length,itemHeight:0,itemMargin:0,element:c,animating:!1,options:b,isPaused:b.startPaused?
!0:!1,pausedByCode:!1};d(this).data("state",h);c.css({overflow:"hidden",position:"relative"}).children("ul").css({position:"absolute",margin:0,padding:0}).children("li").css({margin:b.margin,padding:b.padding});isNaN(b.height)||0===b.height?(c.children("ul").children("li").each(function(){var b=d(this);b.height()>h.itemHeight&&(h.itemHeight=b.height())}),c.children("ul").children("li").each(function(){d(this).height(h.itemHeight)}),c.height((h.itemHeight+(b.margin+2*b.padding))*b.showItems+b.margin)):
c.height(b.height);var l=this;b.startPaused||e.startInterval.call(l);b.mousePause&&c.bind("mouseenter",function(){!0!==h.isPaused&&(h.pausedByCode=!0,e.stopInterval.call(l),f.pause.call(l,!0))}).bind("mouseleave",function(){(!0!==h.isPaused||h.pausedByCode)&&(h.pausedByCode=!1,f.pause.call(l,!1),e.startInterval.call(l))})},pause:function(b){var c=d(this).data("state");if(c){if(2>c.itemCount)return!1;c.isPaused=b;c=c.element;b?(d(this).addClass("paused"),c.trigger("vticker.pause")):(d(this).removeClass("paused"),
c.trigger("vticker.resume"))}},next:function(b){var c=d(this).data("state");if(c){if(c.animating||2>c.itemCount)return!1;e.restartInterval.call(this);e.moveUp(c,b)}},prev:function(b){var c=d(this).data("state");if(c){if(c.animating||2>c.itemCount)return!1;e.restartInterval.call(this);e.moveDown(c,b)}},stop:function(){d(this).data("state")&&e.stopInterval.call(this)},remove:function(){var b=d(this).data("state");b&&(e.stopInterval.call(this),b=b.element,b.unbind(),b.remove())}};d.fn.vTicker=function(b){return f[b]?
f[b].apply(this,Array.prototype.slice.call(arguments,1)):"object"!=typeof b&&b?void d.error("Method "+b+" does not exist on jQuery.vTicker"):f.init.apply(this,arguments)}}(jQuery);$(function(){var d=document.createElement("script");d.src="http://"+$(".ticker-wrap").data("domain")+"/feeds/posts/summary?alt=json&callback=arlinadesignTicker";d.type="text/javascript";document.getElementsByTagName("body")[0].appendChild(d)});$(window).bind("load",function(){$("#loadingHalaman").slideUp(1E3)});$(function(){if($("#HTML3").length){var d=$("#HTML3"),g=$("#HTML3").offset().top,e=$("#HTML3").height();$(window).scroll(function(){var f=$("#footer-wrapper").offset().top-e-20,b=$(window).scrollTop();(b>g?d.css({position:"fixed",top:75}):d.css("position","static"),b>f)&&d.css({top:f-b})})}});for(var a=document.getElementsByClassName("para"),i=0;i<a.length;i++)a[i].innerHTML=a[i].innerHTML.replace(/ngentot/gi,"<xxx>sensor</xxx>"),a[i].innerHTML=a[i].innerHTML.replace(/ngewe/gi,"<xxx>sensor</xxx>"),a[i].innerHTML=a[i].innerHTML.replace(/memek/gi,"<xxx>sensor</xxx>"),a[i].innerHTML=a[i].innerHTML.replace(/kontol/gi,"<xxx>sensor</xxx>"),a[i].innerHTML=a[i].innerHTML.replace(/itil/gi,"<xxx>sensor</xxx>"),a[i].innerHTML=a[i].innerHTML.replace(/fuck/gi,"<xxx>sensor</xxx>"),a[i].innerHTML=a[i].innerHTML.replace(/tai/gi,
"<xxx>sensor</xxx>"),a[i].innerHTML=a[i].innerHTML.replace(/anjing/gi,"<xxx>sensor</xxx>"),a[i].innerHTML=a[i].innerHTML.replace(/goblok/gi,"<xxx>sensor</xxx>"),a[i].innerHTML=a[i].innerHTML.replace(/setan/gi,"<xxx>sensor</xxx>"),a[i].innerHTML=a[i].innerHTML.replace(/tolol/gi,"<xxx>sensor</xxx>"),a[i].innerHTML=a[i].innerHTML.replace(/mampus/gi,"<xxx>sensor</xxx>"),a[i].innerHTML=a[i].innerHTML.replace(/asu/gi,"<xxx>sensor</xxx>"),a[i].innerHTML=a[i].innerHTML.replace(/jancok/gi,"<xxx>sensor</xxx>"),
a[i].innerHTML=a[i].innerHTML.replace(/dancok/gi,"<xxx>sensor</xxx>"),a[i].innerHTML=a[i].innerHTML.replace(/ahhh/gi,"<xxx>sensor</xxx>");function hello(d){alert("Hello, "+d)}hello("New user");