$(function(){if($("#HTML3").length){var c=$("#HTML3"),f=$("#HTML3").offset().top,d=$("#HTML3").height();$(window).scroll(function(){var e=$("#footer-wrapper").offset().top-d-20,a=$(window).scrollTop();(a>f?c.css({position:"fixed",top:55}):c.css("position","static"),a>e)&&c.css({top:e-a})})}});$(window).bind("load",function(){$("#loadingHalaman").slideUp(1E3)});function getauthor(c){for(var f=0;f<c.length;f++)var d=c[f].name.$t;return d}function getmeta(c){var f=c.substring(0,4),d=c.substring(5,7);c=c.substring(8,10);return[,"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][parseInt(d,10)]+" "+c+" "+f}
function arlinadesignTicker(c){var f=document.querySelector("#ticker");c=c.feed.entry;var d="<ul id='ticket-wrapper-inner'>";if(c){for(var e=0;e<c.length;e++){for(var a=c[e],b=0;b<a.link.length;b++)if("alternate"==a.link[b].rel){var g=a.link[b].href;break}try{var k='<img src="'+a.media$thumbnail.url+'"/>'}catch(l){k=""}var b=a.title.$t,p=getauthor(a.author),a=getmeta(a.published.$t),d=d+("<li>"+k+'<h3><a href="'+g+'">'+b+'</a></h3><div class="tickermeta"><span>'+p+"</span> - <span>"+a+"</span></div></li>")}f.innerHTML=
d+"</ul>"}$("#ticker").vTicker()}
!function(c){var f={speed:700,pause:4E3,showItems:1,mousePause:!0,height:0,animate:!0,margin:0,padding:0,startPaused:!1},d={moveUp:function(a,b){d.animate(a,b,"up")},moveDown:function(a,b){d.animate(a,b,"down")},animate:function(a,b,d){var e=a.itemHeight,f=a.options,l=a.element,h=l.children("ul"),m="up"===d?"li:first":"li:last";l.trigger("vticker.beforeTick");var n=h.children(m).clone(!0);if(0<f.height&&(e=h.children("li:first").height()),e+=f.margin+2*f.padding,"down"===d&&h.css("top","-"+e+"px").prepend(n),
b&&b.animate){if(a.animating)return;a.animating=!0;h.animate("up"===d?{top:"-="+e+"px"}:{top:0},f.speed,function(){c(h).children(m).remove();c(h).css("top","0px");a.animating=!1;l.trigger("vticker.afterTick")})}else h.children(m).remove(),h.css("top","0px"),l.trigger("vticker.afterTick");"up"===d&&n.appendTo(h)},nextUsePause:function(){var a=c(this).data("state"),b=a.options;a.isPaused||2>a.itemCount||e.next.call(this,{animate:b.animate})},startInterval:function(){var a=c(this).data("state"),b=this;
a.intervalId=setInterval(function(){d.nextUsePause.call(b)},a.options.pause)},stopInterval:function(){var a=c(this).data("state");a&&(a.intervalId&&clearInterval(a.intervalId),a.intervalId=void 0)},restartInterval:function(){d.stopInterval.call(this);d.startInterval.call(this)}},e={init:function(a){e.stop.call(this);var b=jQuery.extend({},f);a=c.extend(b,a);var b=c(this),g={itemCount:b.children("ul").children("li").length,itemHeight:0,itemMargin:0,element:b,animating:!1,options:a,isPaused:a.startPaused?
!0:!1,pausedByCode:!1};c(this).data("state",g);b.css({overflow:"hidden",position:"relative"}).children("ul").css({position:"absolute",margin:0,padding:0}).children("li").css({margin:a.margin,padding:a.padding});isNaN(a.height)||0===a.height?(b.children("ul").children("li").each(function(){var a=c(this);a.height()>g.itemHeight&&(g.itemHeight=a.height())}),b.children("ul").children("li").each(function(){c(this).height(g.itemHeight)}),b.height((g.itemHeight+(a.margin+2*a.padding))*a.showItems+a.margin)):
b.height(a.height);var k=this;a.startPaused||d.startInterval.call(k);a.mousePause&&b.bind("mouseenter",function(){!0!==g.isPaused&&(g.pausedByCode=!0,d.stopInterval.call(k),e.pause.call(k,!0))}).bind("mouseleave",function(){(!0!==g.isPaused||g.pausedByCode)&&(g.pausedByCode=!1,e.pause.call(k,!1),d.startInterval.call(k))})},pause:function(a){var b=c(this).data("state");if(b){if(2>b.itemCount)return!1;b.isPaused=a;b=b.element;a?(c(this).addClass("paused"),b.trigger("vticker.pause")):(c(this).removeClass("paused"),
b.trigger("vticker.resume"))}},next:function(a){var b=c(this).data("state");if(b){if(b.animating||2>b.itemCount)return!1;d.restartInterval.call(this);d.moveUp(b,a)}},prev:function(a){var b=c(this).data("state");if(b){if(b.animating||2>b.itemCount)return!1;d.restartInterval.call(this);d.moveDown(b,a)}},stop:function(){c(this).data("state")&&d.stopInterval.call(this)},remove:function(){var a=c(this).data("state");a&&(d.stopInterval.call(this),a=a.element,a.unbind(),a.remove())}};c.fn.vTicker=function(a){return e[a]?
e[a].apply(this,Array.prototype.slice.call(arguments,1)):"object"!=typeof a&&a?void c.error("Method "+a+" does not exist on jQuery.vTicker"):e.init.apply(this,arguments)}}(jQuery);$(function(){var c=document.createElement("script");c.src="http://"+$(".ticker-wrap").data("domain")+"/feeds/posts/summary?alt=json&callback=arlinadesignTicker";c.type="text/javascript";document.getElementsByTagName("body")[0].appendChild(c)});